spring:
  threads:
    virtual:
      enabled: true
  application:
    name: imageprocess-api
  datasource:
    url: jdbc:postgresql://localhost:25432/imageprocess
    username: imageprocess
    password: imageprocess
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

polling:
  initial-delay-ms: 5000
  spread-window-ms: 10000
